version: '3'
services:
    app:
        build: .
        container_name: todo-app
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
            - JWT_SECRET=vikalps_random_string
            - NODE_ENV=development
            - PORT=5757
        ports:
            -"5757:5757"
        depends_on:
            - db
        volumes:
            - .:/app