### get request (home page)
GET http://localhost:5757



### Register POST auth/register

POST http://localhost:5757/auth/register
Content-Type: application/json

{
    "username": "san@gmail.com",
    "password": "555555"
}



### Login POST auth/login

POST http://localhost:5757/auth/login
Content-Type: application/json

{
    "username": "san@gmail.com",
    "password": "555555"
}


### Fetch all todos GET /Todos (protected, token needed)
GET http://localhost:5757/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg0NDQzMTQ2LCJleHAiOjE3ODQ1Mjk1NDZ9.8aY92oSTBsAiGoG1RaKmDcWxSZcuK13ynD4r7wURAnA



### Create a new Todo POST /Todos (protected)
POST http://localhost:5757/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg0NDQzMTQ2LCJleHAiOjE3ODQ1Mjk1NDZ9.8aY92oSTBsAiGoG1RaKmDcWxSZcuK13ynD4r7wURAnA
Content-Type: application/json

{ 
    "task": "finishing the sqlite project by saturday."
}

### Update a Todo PUT /Todods/:ID (protected)
PUT http://localhost:5757/todos/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg0NDQzMTQ2LCJleHAiOjE3ODQ1Mjk1NDZ9.8aY92oSTBsAiGoG1RaKmDcWxSZcuK13ynD4r7wURAnA
Content-Type: application/json

{
    "completed": 0
}

