### get request (home page)
GET http://localhost:5757



### Register POST auth/register

POST http://localhost:5757/auth/register
Content-Type: application/json

{
    "username": "san@gmail.com",
    "password": "555555"
}



### Login POST auth/login

POST http://localhost:5757/auth/login
Content-Type: application/json

{
    "username": "san@gmail.com",
    "password": "555555"
}


### Fetch all todos GET /Todos (protected, token needed)
GET http://localhost:5757/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg0NDQ1NDI3LCJleHAiOjE3ODQ1MzE4Mjd9.pkH5vQ49LN2qv-fdYw9cm7QhvRDLnTeQxdp4C-q_MFw


### Create a new Todo POST /Todos (protected)
POST http://localhost:5757/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg0NDQ1NDI3LCJleHAiOjE3ODQ1MzE4Mjd9.pkH5vQ49LN2qv-fdYw9cm7QhvRDLnTeQxdp4C-q_MFw
Content-Type: application/json

{ 
    "task": "finishing the sqlite project by saturday."
}

### Update a Todo PUT /Todods/:ID (protected)
PUT http://localhost:5757/todos/1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg0NDQ1NDI3LCJleHAiOjE3ODQ1MzE4Mjd9.pkH5vQ49LN2qv-fdYw9cm7QhvRDLnTeQxdp4C-q_MFw
Content-Type: application/json

{
    "completed": 1
}

### Delete a Todo DELETE /Todos /:ID (protected)
DELETE http://localhost:5757/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzg0NDQ1NDI3LCJleHAiOjE3ODQ1MzE4Mjd9.pkH5vQ49LN2qv-fdYw9cm7QhvRDLnTeQxdp4C-q_MFw
Content-Type: application/json

